config/routes.rb
Rails.application.routes.draw do

  resources :needs do
    collection do
      match :next, via: [:get, :post]
      get :results
    end

    member do
      post :review
    end
  end

  root to: redirect('/needs')

end

app/models/need.rb
class Need < ActiveRecord::Base
  validates :need_api_id, presence: true
  validates :positive_rating_count, :neutral_rating_count, :negative_rating_count,
              numericality: { only_integer: true }

  VALID_OPINIONS = [
    :positive,
    :neutral,
    :negative,
  ]

  before_save :set_percentage_score

  def to_param
    need_api_id.to_s
  end

  def submit_score(opinion)
    raise "Invalid opinion: '#{opinion}'" unless VALID_OPINIONS.include?(opinion)

    increment("#{opinion}_rating_count", 1)
    increment("total_rating_count", 1)
    save!
  end

  def self.random
    total = self.count
    self.offset(rand(total)).first
  end

private

  def set_percentage_score
    self.percentage_score = calculate_percentage_score
  end

  def calculate_percentage_score
    if total_rating_count == 0 || positive_rating_count == 0
      return 0
    end

    overall_score = positive_rating_count.to_f + (neutral_rating_count.to_f / 2)
    overall_score / total_rating_count.to_f * 100
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController

  def index
  end

  def results
  end

  def next
    redirect_to_random_need
  end

  def show
  end

  def review
    need.submit_score(opinion)
    redirect_to_random_need
  end

private

  def needs_in_order
    scope = Need

    if params[:min].present?
      scope = scope.where('total_rating_count > ?', params[:min])
    end

    @needs ||= scope.order("percentage_score desc").all
  end
  helper_method :needs_in_order

  def need
    @need ||= Need.find_by_need_api_id(params[:id])
  end
  helper_method :need

  def redirect_to_random_need
    redirect_to need_path(Need.random)
  end

  def opinion
    case params[:opinion]
    when 'Looks good' then :positive
    when 'Not sure' then :neutral
    when 'Needs work' then :negative
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/needs_helper.rb
module NeedsHelper

  def humanise_organisation_ids(string)
    (string || "").split(",").map {|str|
      sanitize(str.underscore.humanize.titleize)
    }.join('<br>').html_safe
  end

  def format_percentage_score(percentage)
    string = number_to_percentage(percentage, significant: 4)
    content_tag :span, string, class: class_for_percentage(percentage)
  end

private
  def class_for_percentage(percentage)
    case
    when percentage > 80.0 then 'positive'
    when percentage > 60.0 then 'neutral'
    else
      'negative'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Validate-o-tron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1>Validat-o-tron</h1>
  </header>

  <main>
    <%= yield %>
  </main>

</body>
</html>

app/views/needs/index.html.erb
<h1>User need validation</h1>

<%= button_to "Start &rarr;".html_safe, next_needs_path, class: 'start' %>

<p><%= link_to "See results", results_needs_path %></p>

app/views/needs/results.html.erb
<h1>All needs</h1>

<%= form_tag results_needs_path, class: 'filter', method: :get do %>
  <%= label_tag do %>
    Minimum reviews:
    <%= select_tag "min", options_for_select([["any", ""], ["1", "1"], ["5", "5"], ["10", "10"]], params[:min]) %>
  <% end %>
  <%= submit_tag "Filter", name: nil %>
<% end %>

<table>
  <thead>
    <th>Need ID</th>
    <th>Goal</th>
    <th>Score</th>
    <th class="positive">+</th>
    <th class="neutral">=</th>
    <th class="negative">-</th>
    <th>Total</th>
  </thead>
  <tbody>
    <% needs_in_order.each do |need| %>
    <tr>
      <td><%= need.need_api_id %></td>
      <td><%= truncate(need.goal, length: 100) %></td>
      <td><%= format_percentage_score need.percentage_score %></td>
      <td><%= need.positive_rating_count %></td>
      <td><%= need.neutral_rating_count %></td>
      <td><%= need.negative_rating_count %></td>
      <td><%= need.total_rating_count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/needs/show.html.erb
<article>
  <h1>#<%= need.need_api_id %></h1>

  <section class="need">
    As a <%= need.role %><br>
    I need to <%= need.goal %><br>
    So that <%= need.benefit %>
  </section>

  <dl>
    <dt>Organisations</dt>
    <dd><%= humanise_organisation_ids need.organisation_ids %></dd>
    <dt>Impact</dt>
    <dd><%= need.impact %></dd>
    <dt>Met when</dt>
    <dd><%= need.met_when %></dd>
  </dl>

  <section class="score">
    <dl>
      <dt>Positive ratings</dt>
      <dd><%= need.positive_rating_count %></dd>
      <dt>Neutral ratings</dt>
      <dd><%= need.neutral_rating_count %></dd>
      <dt>Negative ratings</dt>
      <dd><%= need.negative_rating_count %></dd>
      <dt>Percentage score</dt>
      <dd><%= format_percentage_score need.percentage_score %></dd>
    </dl>
  </section>

  <section class="actions">
    <%= button_to "Looks good", review_need_path(need), name: 'opinion', class: 'positive' %>
    <%= button_to "Not sure", review_need_path(need), name: 'opinion', class: 'neutral' %>
    <%= button_to "Needs work", review_need_path(need), name: 'opinion', class: 'negative' %>
    <%= button_to "Skip", next_needs_path, class: 'skip' %>
  </section>
</article>